### PR TITLE
fix(rabbitmq): improve URI assertion

### LINKED ISSUE #1009: Wrong URI validation not allowing to pass query params for amqplib
We have this RegEx validation for RabbitMQ URI here:
https://github.com/golevelup/nestjs/blob/a57a7508be863b326e26175f688df7dd40a67fdf/packages/rabbitmq/src/amqp/utils.ts#L40-L52

It should allow to pass query params like, for example, `frameMax`.

### PR DESCRIPTION
**Pull request by underfisk**
- Fixes the RabbitMQ URI assertion to leverage node `URL` constructor and assert that the protocol is valid

Closes #1009

### CODE REVIEW

**Comment by underfisk** [comment]
@noghartt may i have your 👀  here?

File: packages/rabbitmq/src/amqp/utils.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ export function matchesRoutingKey(
 }
 
 const rabbitMQRegex =
-  /^amqps?:\/\/(([^:]+):([^@]+)@)?([^:/]+)(:[0-9]+)?(\/.*)?$/;
+  /^amqps?:\/\/(?:[^@]+@)?[^:/?#]+(?::\d+)?(?:\/[^?#]*)?(?:\?.*)?$/;
```
Comment (noghartt) [inline packages/rabbitmq/src/amqp/utils.ts]: actually, I thought in doing it in a simple way, just parsing it as a `URL` instance.

We could do something like:
```ts
try {
  const uri = new URL(uri);
  return uri.protocol.startsWith('amqp') || uri.protocol.startsWith('amqps')
} catch (e) {
  // ...
}
```

IMO is less complex than handling RegEx per se, what do you think?

Comment (underfisk) [reply packages/rabbitmq/src/amqp/utils.ts]: Sure, looks like a good alternative. I will review your approach once I have some time free today

**Review by noghartt — APPROVED** [review]
LGTM

**Comment by underfisk** [comment]
Thanks @noghartt 
When @WonderPanda performs the next release, this will be included
