### PR TITLE
fix(rabbitmq): prevent unhandled promise rejection warning

### LINKED ISSUE #259: UnhandledPromiseRejectionWarning when sending message on closed connection
If you use the `amqpConnection.request` when there is no connection yet you get a UnhandledPromiseRejectionWarning.

To reproduce config the RabbitMQModule with a broken url and wait = false
```
RabbitMQModule.forRoot(RabbitMQModule, {
            exchanges: [
                {
                    name: 'amq.topic',
                    type: 'topic',
                },
            ],
            uri: 'amqp://invalid:invalid@localhost:5672',
            connectionInitOptions: { wait: false },
        }),
```

Then use the `amqpConnection.request` like this:
```
try {
            const response = await this.amqpConnection.request<string>({
                exchange: 'amq.topic',
                routingKey: 'some_topic',
                payload: 'example',
                timeout: 10000, 
            });
        } catch (e) {
            console.log("error", e);           
        }
```

Now you will first get an UnhandledPromiseRejectionWarning before the catch logs the  "Error: Failed to receive response within timeout of 10000ms"

As far as i can see this is because the connection.ts `request` method is not try..catching the `publish` function.
The `publish` function throws an error when there is no connection

### PR DESCRIPTION
**Pull request by arjenvdhave**
Catch and rethrow errors from the publish function to prevent UnhandledPromiseRejectionWarning

fix #259

### CODE REVIEW

File: packages/rabbitmq/src/amqp/connection.ts [hunk 1]
```diff
@@ -201,11 +202,21 @@ export class AmqpConnection {
...
+        payload,
+        {
+          replyTo: DIRECT_REPLY_QUEUE,
+          correlationId,
+        }
+      );
+    } catch (error) {
+      //Catching errors from the publish function to prevent UnhandledPromiseRejectionWarning
+      //Rethrow error so the caller of this function can catch the error.
+      throw e;
```
Comment (WonderPanda) [inline packages/rabbitmq/src/amqp/connection.ts]: @arjenvdhave This isn't the error, its an import for `express`.

**Review by WonderPanda — CHANGES_REQUESTED** [review]

File: packages/rabbitmq/src/amqp/connection.ts (hunk 1 above)
Comment (arjenvdhave) [reply packages/rabbitmq/src/amqp/connection.ts]: ah damn, sorry my vscode made this weird import

**Comment by WonderPanda** [comment]
@arjenvdhave Looking at this some more, I don't think we actually need the try/catch here. All that is required for the error to bubble up properly is the `await` in front of `this.publish` so that the promise isn't treated in a fire and forget manner.

**Comment by arjenvdhave** [comment]
Yes the try catch seems unnecessary indeed, will remove it

**Review by WonderPanda — APPROVED** [review]
